part of "work_item_detail_bloc.dart";

final _workItem = WorkItemRecord(
  id: 1,
  projectId: 1,
  name: "Work 1 ABC",
  nameShort: "Work 1",
  description: "",
  taskCount: 23,
  progression: 0.1,
  startDate: DateTime.now(),
  isCompleted: false,
  isActive: true,
);

const _workItemList = [
  TaskRecord(
    id: 1,
    workId: 1,
    name: "Task 1 ABC",
    nameShort: "Task 1",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
  TaskRecord(
    id: 2,
    workId: 1,
    name: "Task 2 DEF",
    nameShort: "Task 2",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
  TaskRecord(
    id: 3,
    workId: 1,
    name: "Task 3 GHI",
    nameShort: "Task 3",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
  TaskRecord(
    id: 1,
    workId: 1,
    name: "Task 1 ABC",
    nameShort: "Task 1",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
  TaskRecord(
    id: 2,
    workId: 1,
    name: "Task 2 DEF",
    nameShort: "Task 2",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
  TaskRecord(
    id: 3,
    workId: 1,
    name: "Task 3 GHI",
    nameShort: "Task 3",
    description: "",
    status: TaskStatus.active,
    // type: TaskType.timestamp,
    isActive: true,
  ),
];
